--liquibase formatted sql

--changeset tony:create-account
create TABLE ACCOUNT (
  ID BIGSERIAL PRIMARY KEY,
  NUMBER VARCHAR(36) NOT NULL UNIQUE ,
  CREATE_TIME TIMESTAMP NOT NULL,
  BALANCE NUMERIC(19,4),
  ACC_NAME VARCHAR(50)
);

--changeset tony:create-account-transaction
create TABLE ACCOUNT_TRANSACTION (
  ID BIGSERIAL PRIMARY KEY,
  FROM_ACC BIGINT NOT NULL REFERENCES ACCOUNT(ID),
  TO_ACC BIGINT NOT NULL REFERENCES ACCOUNT(ID),
  TRANSACTION_TIME TIMESTAMP NOT NULL,
  AMOUNT NUMERIC(19,4)
);
