--liquibase formatted sql

--changeset tony:create-account
create TABLE ACCOUNT (
  ID BIGSERIAL,
  NUMBER VARCHAR(36) NOT NULL UNIQUE ,
  CREATE_DATE TIMESTAMP,
  BALANCE NUMERIC,
  ACC_NAME VARCHAR(50)
);

--changeset tony:create-account-transaction
create TABLE ACCOUNT_TRANSACTION (
  ID BIGSERIAL,
  FROM_ACC BIGINT NOT NULL ,
  TO_ACC BIGINT NOT NULL,
  TRANSACTION_TIME TIMESTAMP NOT NULL,
  AMOUNT NUMERIC
);
